from __future__ import annotations

from .types import DAMAGE_MASK_LIVING, DAMAGE_MASK_TERRAIN, LifetimeMode, MaterialFamily, MaterialRegistry, MatterState, PhaseRule, VariantDef


DEFAULT_MOBILE_VELOCITY_DECAY = 0.92
DEFAULT_STATIC_VELOCITY_DECAY = 0.96
DEFAULT_SOLID_WIND_COUPLING = 1.5
DEFAULT_SOLID_WIND_VERTICAL_FACTOR = 0.1


def _default_motion_profile(matter_state: MatterState, *, support_bearing: bool) -> dict[str, float | bool]:
    if matter_state == MatterState.SOLID:
        if support_bearing:
            return {
                "mobility": 0.0,
                "pressure_response": 0.0,
                "gravity_scale": 0.0,
                "buoyancy_scale": 0.0,
                "thermal_motion_scale": 0.0,
                "wind_coupling": 0.0,
                "wind_vertical_factor": 0.0,
                "downward_blocked_diagonal_fallback": False,
                "velocity_decay": DEFAULT_STATIC_VELOCITY_DECAY,
            }
        return {
            "mobility": 1.0,
            "pressure_response": 1.0,
            "gravity_scale": 1.0,
            "buoyancy_scale": 0.0,
            "thermal_motion_scale": 0.0,
            "wind_coupling": DEFAULT_SOLID_WIND_COUPLING,
            "wind_vertical_factor": DEFAULT_SOLID_WIND_VERTICAL_FACTOR,
            "downward_blocked_diagonal_fallback": True,
            "velocity_decay": DEFAULT_MOBILE_VELOCITY_DECAY,
        }
    if matter_state == MatterState.LIQUID:
        return {
            "mobility": 1.0,
            "pressure_response": 1.0,
            "gravity_scale": 1.0,
            "buoyancy_scale": 0.0,
            "thermal_motion_scale": 1.0,
            "wind_coupling": 0.0,
            "wind_vertical_factor": 0.0,
            "downward_blocked_diagonal_fallback": False,
            "velocity_decay": DEFAULT_MOBILE_VELOCITY_DECAY,
        }
    return {
        "mobility": 1.0,
        "pressure_response": 1.0,
        "gravity_scale": 0.0,
        "buoyancy_scale": 1.0,
        "thermal_motion_scale": 1.0,
        "wind_coupling": 0.0,
        "wind_vertical_factor": 0.0,
        "downward_blocked_diagonal_fallback": False,
        "velocity_decay": DEFAULT_MOBILE_VELOCITY_DECAY,
    }


def _variant(
    variant_id: str,
    *,
    matter_state: MatterState,
    density: float,
    hardness: float,
    friction: float,
    viscosity: float,
    thermal_conductivity: float,
    heat_capacity: float,
    support_bearing: bool,
    support_transmission: bool,
    base_temperature: float,
    reaction_min_temperature: float = 0.0,
    reaction_max_temperature: float = 0.0,
    melt_temperature: float | None = None,
    freeze_temperature: float | None = None,
    boil_temperature: float | None = None,
    integrity_decay_from_heat: float = 0.0,
    reaction_strength: float = 0.0,
    reaction_energy: float = 0.0,
    reaction_preserves_self: bool = True,
    lifetime_mode: LifetimeMode = LifetimeMode.NONE,
    ignite_target_family_id: str | None = None,
    ignite_target_variant_id: str | None = None,
    damage_mask: tuple[str, ...] = (),
    convert_mode: str = "none",
    mobility: float | None = None,
    pressure_response: float | None = None,
    gravity_scale: float | None = None,
    buoyancy_scale: float | None = None,
    thermal_motion_scale: float | None = None,
    wind_coupling: float | None = None,
    wind_vertical_factor: float | None = None,
    downward_blocked_diagonal_fallback: bool | None = None,
    velocity_decay: float | None = None,
    liquid_contact_heat_exchange_multiplier: float = 1.0,
    same_variant_heat_exchange_multiplier: float = 1.0,
    render_color: tuple[int, int, int] = (255, 255, 255),
) -> VariantDef:
    motion_profile = _default_motion_profile(
        matter_state,
        support_bearing=support_bearing,
    )
    return VariantDef(
        variant_id=variant_id,
        matter_state=matter_state,
        density=density,
        hardness=hardness,
        friction=friction,
        viscosity=viscosity,
        thermal_conductivity=thermal_conductivity,
        heat_capacity=heat_capacity,
        support_bearing=support_bearing,
        support_transmission=support_transmission,
        base_temperature=base_temperature,
        reaction_min_temperature=reaction_min_temperature,
        reaction_max_temperature=reaction_max_temperature,
        melt_temperature=melt_temperature,
        freeze_temperature=freeze_temperature,
        boil_temperature=boil_temperature,
        integrity_decay_from_heat=integrity_decay_from_heat,
        reaction_strength=reaction_strength,
        reaction_energy=reaction_energy,
        reaction_preserves_self=reaction_preserves_self,
        lifetime_mode=lifetime_mode,
        ignite_target_family_id=ignite_target_family_id,
        ignite_target_variant_id=ignite_target_variant_id,
        damage_mask=damage_mask,
        convert_mode=convert_mode,
        mobility=float(motion_profile["mobility"] if mobility is None else mobility),
        pressure_response=float(motion_profile["pressure_response"] if pressure_response is None else pressure_response),
        gravity_scale=float(motion_profile["gravity_scale"] if gravity_scale is None else gravity_scale),
        buoyancy_scale=float(motion_profile["buoyancy_scale"] if buoyancy_scale is None else buoyancy_scale),
        thermal_motion_scale=float(motion_profile["thermal_motion_scale"] if thermal_motion_scale is None else thermal_motion_scale),
        wind_coupling=float(motion_profile["wind_coupling"] if wind_coupling is None else wind_coupling),
        wind_vertical_factor=float(
            motion_profile["wind_vertical_factor"] if wind_vertical_factor is None else wind_vertical_factor
        ),
        downward_blocked_diagonal_fallback=bool(
            motion_profile["downward_blocked_diagonal_fallback"]
            if downward_blocked_diagonal_fallback is None
            else downward_blocked_diagonal_fallback
        ),
        velocity_decay=float(motion_profile["velocity_decay"] if velocity_decay is None else velocity_decay),
        liquid_contact_heat_exchange_multiplier=liquid_contact_heat_exchange_multiplier,
        same_variant_heat_exchange_multiplier=same_variant_heat_exchange_multiplier,
        render_color=render_color,
    )


def build_material_registry() -> MaterialRegistry:
    families: dict[str, MaterialFamily] = {}

    families["empty"] = MaterialFamily(
        family_id="empty",
        name="empty",
        default_variant="empty",
        collapse_target=None,
        variants={
            "empty": _variant(
                "empty",
                matter_state=MatterState.GAS,
                density=1.0,
                hardness=0.0,
                friction=0.0,
                viscosity=0.0,
                thermal_conductivity=0.35,
                heat_capacity=1.0,
                support_bearing=False,
                support_transmission=False,
                base_temperature=20.0,
                render_color=(0, 0, 0),
            )
        },
    )

    families["stone"] = MaterialFamily(
        family_id="stone",
        name="stone",
        default_variant="stone_platform",
        collapse_target="stone_powder",
        variants={
            "stone_platform": _variant(
                "stone_platform",
                matter_state=MatterState.SOLID,
                density=2.8,
                hardness=0.95,
                friction=0.8,
                viscosity=0.0,
                thermal_conductivity=0.9,
                heat_capacity=1.2,
                support_bearing=True,
                support_transmission=True,
                base_temperature=20.0,
                melt_temperature=1400.0,
                integrity_decay_from_heat=0.0003,
                render_color=(110, 110, 120),
            ),
            "stone_powder": _variant(
                "stone_powder",
                matter_state=MatterState.SOLID,
                density=2.2,
                hardness=0.45,
                friction=0.55,
                viscosity=0.0,
                thermal_conductivity=0.55,
                heat_capacity=1.0,
                support_bearing=False,
                support_transmission=False,
                base_temperature=20.0,
                melt_temperature=1300.0,
                integrity_decay_from_heat=0.0001,
                render_color=(130, 130, 138),
            ),
            "magma": _variant(
                "magma",
                matter_state=MatterState.LIQUID,
                density=2.4,
                hardness=0.05,
                friction=0.15,
                viscosity=0.9,
                thermal_conductivity=1.0,
                heat_capacity=1.8,
                support_bearing=False,
                support_transmission=False,
                base_temperature=1450.0,
                render_color=(255, 110, 0),
            ),
        },
        phase_map=(
            PhaseRule("stone_platform", "magma", above_temperature=1400.0),
            PhaseRule("stone_powder", "magma", above_temperature=1300.0),
            PhaseRule("magma", "stone_platform", below_temperature=900.0),
        ),
        render_profile={"glow": False},
    )

    families["sand"] = MaterialFamily(
        family_id="sand",
        name="sand",
        default_variant="sand_powder",
        collapse_target="sand_powder",
        variants={
            "sand_powder": _variant(
                "sand_powder",
                matter_state=MatterState.SOLID,
                density=1.7,
                hardness=0.2,
                friction=0.45,
                viscosity=0.0,
                thermal_conductivity=0.3,
                heat_capacity=0.9,
                support_bearing=False,
                support_transmission=False,
                base_temperature=20.0,
                melt_temperature=1200.0,
                render_color=(210, 190, 120),
            ),
        },
        phase_map=(
            PhaseRule(
                "sand_powder",
                "molten_glass",
                target_family_id="glass",
                above_temperature=1200.0,
            ),
        ),
    )

    families["glass"] = MaterialFamily(
        family_id="glass",
        name="glass",
        default_variant="glass_platform",
        collapse_target="glass_shards",
        variants={
            "glass_platform": _variant(
                "glass_platform",
                matter_state=MatterState.SOLID,
                density=2.5,
                hardness=0.7,
                friction=0.6,
                viscosity=0.0,
                thermal_conductivity=0.45,
                heat_capacity=0.8,
                support_bearing=True,
                support_transmission=True,
                base_temperature=20.0,
                melt_temperature=850.0,
                integrity_decay_from_heat=0.00045,
                render_color=(180, 220, 235),
            ),
            "glass_shards": _variant(
                "glass_shards",
                matter_state=MatterState.SOLID,
                density=2.1,
                hardness=0.35,
                friction=0.4,
                viscosity=0.0,
                thermal_conductivity=0.28,
                heat_capacity=0.8,
                support_bearing=False,
                support_transmission=False,
                base_temperature=20.0,
                melt_temperature=800.0,
                integrity_decay_from_heat=0.0002,
                render_color=(150, 190, 210),
            ),
            "molten_glass": _variant(
                "molten_glass",
                matter_state=MatterState.LIQUID,
                density=2.3,
                hardness=0.03,
                friction=0.1,
                viscosity=0.95,
                thermal_conductivity=0.5,
                heat_capacity=1.4,
                support_bearing=False,
                support_transmission=False,
                base_temperature=1000.0,
                render_color=(255, 180, 90),
            ),
        },
        phase_map=(
            PhaseRule("glass_platform", "molten_glass", above_temperature=850.0),
            PhaseRule("glass_shards", "molten_glass", above_temperature=800.0),
            PhaseRule("molten_glass", "glass_platform", below_temperature=650.0),
        ),
    )

    families["iron"] = MaterialFamily(
        family_id="iron",
        name="iron",
        default_variant="iron_platform",
        collapse_target="iron_grit",
        variants={
            "iron_platform": _variant(
                "iron_platform",
                matter_state=MatterState.SOLID,
                density=3.2,
                hardness=1.0,
                friction=0.75,
                viscosity=0.0,
                thermal_conductivity=1.2,
                heat_capacity=0.7,
                support_bearing=True,
                support_transmission=True,
                base_temperature=20.0,
                melt_temperature=1538.0,
                integrity_decay_from_heat=0.0002,
                render_color=(150, 150, 160),
            ),
            "iron_grit": _variant(
                "iron_grit",
                matter_state=MatterState.SOLID,
                density=2.9,
                hardness=0.5,
                friction=0.55,
                viscosity=0.0,
                thermal_conductivity=0.75,
                heat_capacity=0.8,
                support_bearing=False,
                support_transmission=False,
                base_temperature=20.0,
                melt_temperature=1450.0,
                integrity_decay_from_heat=0.0001,
                render_color=(120, 120, 130),
            ),
            "molten_iron": _variant(
                "molten_iron",
                matter_state=MatterState.LIQUID,
                density=3.0,
                hardness=0.02,
                friction=0.1,
                viscosity=0.85,
                thermal_conductivity=1.1,
                heat_capacity=1.0,
                support_bearing=False,
                support_transmission=False,
                base_temperature=1600.0,
                render_color=(255, 140, 70),
            ),
        },
        phase_map=(
            PhaseRule("iron_platform", "molten_iron", above_temperature=1538.0),
            PhaseRule("iron_grit", "molten_iron", above_temperature=1450.0),
            PhaseRule("molten_iron", "iron_platform", below_temperature=1200.0),
        ),
    )

    families["water"] = MaterialFamily(
        family_id="water",
        name="water",
        default_variant="water",
        collapse_target="water",
        variants={
            "ice": _variant(
                "ice",
                matter_state=MatterState.SOLID,
                density=1.0,
                hardness=0.55,
                friction=0.45,
                viscosity=0.0,
                thermal_conductivity=0.25,
                heat_capacity=40.0,
                support_bearing=True,
                support_transmission=True,
                base_temperature=-5.0,
                melt_temperature=8.0,
                integrity_decay_from_heat=0.0004,
                render_color=(200, 235, 255),
            ),
            "water": _variant(
                "water",
                matter_state=MatterState.LIQUID,
                density=1.0,
                hardness=0.0,
                friction=0.05,
                viscosity=0.25,
                thermal_conductivity=0.5,
                heat_capacity=1.5,
                support_bearing=False,
                support_transmission=False,
                base_temperature=20.0,
                freeze_temperature=0.0,
                boil_temperature=100.0,
                render_color=(60, 120, 255),
            ),
            "steam": _variant(
                "steam",
                matter_state=MatterState.GAS,
                density=0.85,
                hardness=0.0,
                friction=0.02,
                viscosity=0.05,
                thermal_conductivity=0.06,
                heat_capacity=8.0,
                support_bearing=False,
                support_transmission=False,
                base_temperature=120.0,
                freeze_temperature=65.0,
                liquid_contact_heat_exchange_multiplier=30.0,
                same_variant_heat_exchange_multiplier=80.0,
                render_color=(220, 220, 220),
            ),
        },
        phase_map=(
            PhaseRule("water", "ice", below_temperature=-3.0),
            PhaseRule("water", "steam", above_temperature=100.0),
            PhaseRule("ice", "water", above_temperature=8.0),
            PhaseRule("steam", "water", below_temperature=65.0),
        ),
    )

    families["acid"] = MaterialFamily(
        family_id="acid",
        name="acid",
        default_variant="acid_liquid",
        collapse_target="acid_liquid",
        variants={
            "acid_liquid": _variant(
                "acid_liquid",
                matter_state=MatterState.LIQUID,
                density=1.1,
                hardness=0.0,
                friction=0.04,
                viscosity=0.3,
                thermal_conductivity=0.35,
                heat_capacity=1.0,
                support_bearing=False,
                support_transmission=False,
                base_temperature=20.0,
                boil_temperature=80.0,
                reaction_strength=0.35,
                reaction_preserves_self=False,
                damage_mask=("terrain",),
                convert_mode="self",
                render_color=(140, 255, 90),
            ),
            "acid_gas": _variant(
                "acid_gas",
                matter_state=MatterState.GAS,
                density=1.1,
                hardness=0.0,
                friction=0.01,
                viscosity=0.08,
                thermal_conductivity=0.16,
                heat_capacity=0.7,
                support_bearing=False,
                support_transmission=False,
                base_temperature=90.0,
                freeze_temperature=55.0,
                reaction_strength=0.18,
                reaction_preserves_self=False,
                damage_mask=("terrain",),
                convert_mode="self",
                render_color=(200, 255, 150),
            ),
        },
        phase_map=(
            PhaseRule("acid_liquid", "acid_gas", above_temperature=80.0),
            PhaseRule("acid_gas", "acid_liquid", below_temperature=55.0),
        ),
        reaction_profile={"max_generation": 2},
    )

    families["poison"] = MaterialFamily(
        family_id="poison",
        name="poison",
        default_variant="poison_liquid",
        collapse_target="poison_liquid",
        variants={
            "poison_liquid": _variant(
                "poison_liquid",
                matter_state=MatterState.LIQUID,
                density=0.95,
                hardness=0.0,
                friction=0.04,
                viscosity=0.35,
                thermal_conductivity=0.28,
                heat_capacity=1.0,
                support_bearing=False,
                support_transmission=False,
                base_temperature=20.0,
                boil_temperature=60.0,
                reaction_strength=0.3,
                damage_mask=("living",),
                render_color=(100, 200, 90),
            ),
            "poison_gas": _variant(
                "poison_gas",
                matter_state=MatterState.GAS,
                density=1.05,
                hardness=0.0,
                friction=0.01,
                viscosity=0.06,
                thermal_conductivity=0.12,
                heat_capacity=0.6,
                support_bearing=False,
                support_transmission=False,
                base_temperature=75.0,
                freeze_temperature=35.0,
                reaction_strength=0.22,
                damage_mask=("living",),
                render_color=(160, 230, 140),
            ),
        },
        phase_map=(
            PhaseRule("poison_liquid", "poison_gas", above_temperature=60.0),
            PhaseRule("poison_gas", "poison_liquid", below_temperature=35.0),
        ),
        reaction_profile={"damage_mask": ["living"]},
    )

    families["tar"] = MaterialFamily(
        family_id="tar",
        name="tar",
        default_variant="tar_liquid",
        collapse_target="tar_liquid",
        variants={
            "tar_liquid": _variant(
                "tar_liquid",
                matter_state=MatterState.LIQUID,
                density=1.3,
                hardness=0.0,
                friction=0.1,
                viscosity=0.95,
                thermal_conductivity=0.18,
                heat_capacity=1.2,
                support_bearing=False,
                support_transmission=False,
                base_temperature=20.0,
                reaction_min_temperature=120.0,
                ignite_target_family_id="fire",
                ignite_target_variant_id="fire",
                reaction_strength=0.45,
                damage_mask=("terrain",),
                convert_mode="empty",
                render_color=(40, 30, 25),
            ),
            "tar_smoke": _variant(
                "tar_smoke",
                matter_state=MatterState.GAS,
                density=0.95,
                hardness=0.0,
                friction=0.01,
                viscosity=0.1,
                thermal_conductivity=0.1,
                heat_capacity=0.7,
                support_bearing=False,
                support_transmission=False,
                base_temperature=150.0,
                render_color=(70, 70, 70),
            ),
        },
        phase_map=(
            PhaseRule("tar_liquid", "tar_smoke", above_temperature=140.0),
        ),
        reaction_profile={"damage_mask": ["terrain"]},
        render_profile={"smoke": True},
    )

    families["fire"] = MaterialFamily(
        family_id="fire",
        name="fire",
        default_variant="fire",
        collapse_target=None,
        variants={
            "fire": _variant(
                "fire",
                matter_state=MatterState.GAS,
                density=0.2,
                hardness=0.0,
                friction=0.0,
                viscosity=0.0,
                thermal_conductivity=0.2,
                heat_capacity=0.4,
                support_bearing=False,
                support_transmission=False,
                base_temperature=600.0,
                reaction_energy=45.0,
                reaction_strength=0.5,
                lifetime_mode=LifetimeMode.DECAY_WITH_AGE,
                damage_mask=("terrain", "living"),
                convert_mode="empty",
                render_color=(255, 120, 30),
            ),
        },
        reaction_profile={"max_age": 6.0, "ambient_fade_temperature": 120.0, "damage_mask": ["terrain", "living"]},
        render_profile={"glow": True},
    )

    # ── Oil (lighter than water, flammable) ──
    families["oil"] = MaterialFamily(
        family_id="oil",
        name="oil",
        default_variant="oil_liquid",
        collapse_target="oil_liquid",
        variants={
            "oil_liquid": _variant(
                "oil_liquid",
                matter_state=MatterState.LIQUID,
                density=0.85,
                hardness=0.0,
                friction=0.06,
                viscosity=0.6,
                thermal_conductivity=0.22,
                heat_capacity=1.1,
                support_bearing=False,
                support_transmission=False,
                base_temperature=20.0,
                reaction_min_temperature=100.0,
                ignite_target_family_id="fire",
                ignite_target_variant_id="fire",
                boil_temperature=250.0,
                reaction_strength=0.5,
                damage_mask=("terrain",),
                convert_mode="empty",
                render_color=(60, 50, 20),
            ),
            "oil_smoke": _variant(
                "oil_smoke",
                matter_state=MatterState.GAS,
                density=0.9,
                hardness=0.0,
                friction=0.01,
                viscosity=0.08,
                thermal_conductivity=0.08,
                heat_capacity=0.7,
                support_bearing=False,
                support_transmission=False,
                base_temperature=150.0,
                freeze_temperature=80.0,
                render_color=(80, 70, 60),
            ),
        },
        phase_map=(
            PhaseRule("oil_liquid", "oil_smoke", above_temperature=250.0),
            PhaseRule("oil_smoke", "oil_liquid", below_temperature=80.0),
        ),
        reaction_profile={"damage_mask": ["terrain"]},
    )

    # ── Magic acid (persistent corrosive, heavier than water) ──
    families["magic_acid"] = MaterialFamily(
        family_id="magic_acid",
        name="magic_acid",
        default_variant="magic_acid_liquid",
        collapse_target="magic_acid_liquid",
        variants={
            "magic_acid_liquid": _variant(
                "magic_acid_liquid",
                matter_state=MatterState.LIQUID,
                density=1.3,
                hardness=0.0,
                friction=0.04,
                viscosity=0.35,
                thermal_conductivity=0.4,
                heat_capacity=1.2,
                support_bearing=False,
                support_transmission=False,
                base_temperature=20.0,
                boil_temperature=120.0,
                reaction_strength=0.6,
                reaction_preserves_self=True,
                damage_mask=("terrain", "living"),
                convert_mode="self",
                render_color=(200, 255, 40),
            ),
            "magic_acid_gas": _variant(
                "magic_acid_gas",
                matter_state=MatterState.GAS,
                density=1.2,
                hardness=0.0,
                friction=0.01,
                viscosity=0.08,
                thermal_conductivity=0.18,
                heat_capacity=0.8,
                support_bearing=False,
                support_transmission=False,
                base_temperature=130.0,
                freeze_temperature=60.0,
                reaction_strength=0.3,
                reaction_preserves_self=True,
                damage_mask=("terrain", "living"),
                convert_mode="self",
                render_color=(240, 255, 120),
            ),
        },
        phase_map=(
            PhaseRule("magic_acid_liquid", "magic_acid_gas", above_temperature=120.0),
            PhaseRule("magic_acid_gas", "magic_acid_liquid", below_temperature=60.0),
        ),
        reaction_profile={"damage_mask": ["terrain", "living"], "max_generation": 3},
    )

    # ── Obsidian (harder, darker stone; falling + non-falling variants) ──
    families["obsidian"] = MaterialFamily(
        family_id="obsidian",
        name="obsidian",
        default_variant="obsidian_platform",
        collapse_target="obsidian_shards",
        variants={
            "obsidian_platform": _variant(
                "obsidian_platform",
                matter_state=MatterState.SOLID,
                density=3.0,
                hardness=1.5,
                friction=0.85,
                viscosity=0.0,
                thermal_conductivity=0.95,
                heat_capacity=1.4,
                support_bearing=True,
                support_transmission=True,
                base_temperature=20.0,
                melt_temperature=1600.0,
                integrity_decay_from_heat=0.00015,
                render_color=(40, 20, 50),
            ),
            "obsidian_falling": _variant(
                "obsidian_falling",
                matter_state=MatterState.SOLID,
                density=3.0,
                hardness=1.5,
                friction=0.85,
                viscosity=0.0,
                thermal_conductivity=0.95,
                heat_capacity=1.4,
                support_bearing=False,
                support_transmission=False,
                base_temperature=20.0,
                melt_temperature=1600.0,
                integrity_decay_from_heat=0.00015,
                render_color=(40, 20, 50),
            ),
            "obsidian_shards": _variant(
                "obsidian_shards",
                matter_state=MatterState.SOLID,
                density=2.6,
                hardness=0.55,
                friction=0.5,
                viscosity=0.0,
                thermal_conductivity=0.6,
                heat_capacity=1.1,
                support_bearing=False,
                support_transmission=False,
                base_temperature=20.0,
                melt_temperature=1400.0,
                render_color=(55, 30, 65),
            ),
        },
        phase_map=(
            PhaseRule("obsidian_platform", "magma", target_family_id="stone", above_temperature=1600.0),
            PhaseRule("obsidian_falling", "magma", target_family_id="stone", above_temperature=1600.0),
            PhaseRule("obsidian_shards", "magma", target_family_id="stone", above_temperature=1400.0),
        ),
    )

    # ── Snow (ice powder, melts to water) ──
    families["snow"] = MaterialFamily(
        family_id="snow",
        name="snow",
        default_variant="snow_powder",
        collapse_target="snow_powder",
        variants={
            "snow_powder": _variant(
                "snow_powder",
                matter_state=MatterState.SOLID,
                density=0.4,
                hardness=0.15,
                friction=0.3,
                viscosity=0.0,
                thermal_conductivity=0.12,
                heat_capacity=0.8,
                support_bearing=False,
                support_transmission=False,
                base_temperature=-5.0,
                melt_temperature=5.0,
                render_color=(240, 245, 255),
            ),
        },
        phase_map=(
            PhaseRule("snow_powder", "water", target_family_id="water", above_temperature=5.0),
        ),
    )

    # ── Wood (growable, flammable solid) ──
    families["wood"] = MaterialFamily(
        family_id="wood",
        name="wood",
        default_variant="wood_platform",
        collapse_target="wood_powder",
        variants={
            "wood_platform": _variant(
                "wood_platform",
                matter_state=MatterState.SOLID,
                density=0.6,
                hardness=0.4,
                friction=0.7,
                viscosity=0.0,
                thermal_conductivity=0.2,
                heat_capacity=1.5,
                support_bearing=True,
                support_transmission=True,
                base_temperature=20.0,
                reaction_min_temperature=200.0,
                integrity_decay_from_heat=0.0008,
                ignite_target_family_id="fire",
                ignite_target_variant_id="fire",
                render_color=(140, 100, 50),
            ),
            "wood_powder": _variant(
                "wood_powder",
                matter_state=MatterState.SOLID,
                density=0.35,
                hardness=0.2,
                friction=0.35,
                viscosity=0.0,
                thermal_conductivity=0.15,
                heat_capacity=1.0,
                support_bearing=False,
                support_transmission=False,
                base_temperature=20.0,
                reaction_min_temperature=150.0,
                render_color=(160, 120, 70),
            ),
        },
        reaction_profile={"max_generation": 6},
    )

    # ── Grass (growable, flammable, lighter than wood) ──
    families["grass"] = MaterialFamily(
        family_id="grass",
        name="grass",
        default_variant="grass_platform",
        collapse_target="grass_powder",
        variants={
            "grass_platform": _variant(
                "grass_platform",
                matter_state=MatterState.SOLID,
                density=0.5,
                hardness=0.3,
                friction=0.65,
                viscosity=0.0,
                thermal_conductivity=0.18,
                heat_capacity=1.3,
                support_bearing=True,
                support_transmission=True,
                base_temperature=20.0,
                reaction_min_temperature=150.0,
                integrity_decay_from_heat=0.001,
                ignite_target_family_id="fire",
                ignite_target_variant_id="fire",
                render_color=(80, 160, 50),
            ),
            "grass_powder": _variant(
                "grass_powder",
                matter_state=MatterState.SOLID,
                density=0.3,
                hardness=0.15,
                friction=0.3,
                viscosity=0.0,
                thermal_conductivity=0.12,
                heat_capacity=0.9,
                support_bearing=False,
                support_transmission=False,
                base_temperature=20.0,
                reaction_min_temperature=100.0,
                render_color=(100, 170, 70),
            ),
        },
        reaction_profile={"max_generation": 4},
    )

    # ── Wood plank (decorative variant, no grow) ──
    families["wood_plank"] = MaterialFamily(
        family_id="wood_plank",
        name="wood_plank",
        default_variant="wood_plank",
        collapse_target="wood_plank_powder",
        variants={
            "wood_plank": _variant(
                "wood_plank",
                matter_state=MatterState.SOLID,
                density=0.6,
                hardness=0.4,
                friction=0.7,
                viscosity=0.0,
                thermal_conductivity=0.2,
                heat_capacity=1.5,
                support_bearing=True,
                support_transmission=True,
                base_temperature=20.0,
                reaction_min_temperature=200.0,
                ignite_target_family_id="fire",
                ignite_target_variant_id="fire",
                integrity_decay_from_heat=0.0008,
                render_color=(170, 140, 80),
            ),
            "wood_plank_powder": _variant(
                "wood_plank_powder",
                matter_state=MatterState.SOLID,
                density=0.35,
                hardness=0.2,
                friction=0.35,
                viscosity=0.0,
                thermal_conductivity=0.15,
                heat_capacity=1.0,
                support_bearing=False,
                support_transmission=False,
                base_temperature=20.0,
                render_color=(190, 160, 100),
            ),
        },
    )

    # ── Stone: add falling variant ──
    # (stone family already created above; add variant)
    stone_variants = families["stone"].variants
    stone_variants["stone_falling"] = _variant(
        "stone_falling",
        matter_state=MatterState.SOLID,
        density=2.8,
        hardness=0.95,
        friction=0.8,
        viscosity=0.0,
        thermal_conductivity=0.9,
        heat_capacity=1.2,
        support_bearing=False,
        support_transmission=False,
        base_temperature=20.0,
        melt_temperature=1400.0,
        integrity_decay_from_heat=0.0003,
        render_color=(110, 110, 120),  # same as stone_platform
    )

    # ── Entity placeholder (invisible, blocks material, bears weight) ──
    # Single variant for all entities; owner distinguished by CellState.generation.
    families["entity_placeholder"] = MaterialFamily(
        family_id="entity_placeholder",
        name="entity_placeholder",
        default_variant="placeholder",
        collapse_target=None,
        variants={
            "placeholder": _variant(
                "placeholder",
                matter_state=MatterState.SOLID,
                density=2.0,
                hardness=2.0,
                friction=0.9,
                viscosity=0.0,
                thermal_conductivity=0.5,
                heat_capacity=2.0,
                support_bearing=True,
                support_transmission=True,
                base_temperature=20.0,
                mobility=0.0,
                pressure_response=0.0,
                gravity_scale=0.0,
                render_color=(0, 0, 0),
            ),
        },
    )

    variants = {
        (family_id, variant_id): variant
        for family_id, family in families.items()
        for variant_id, variant in family.variants.items()
    }
    return MaterialRegistry(families=families, variants=variants)
