from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from slm.data_generation import STYLE_RECIPES
from slm.io_utils import write_jsonl


SEED_SPELLS_V2 = [
    ("semi_classical_balanced", "holy_fire", "炽焰出掌, 替我开前路."),
    ("semi_classical_literary", "holy_fire", "金火自掌心漫起, 像晨星一路烧进前尘."),
    ("ritual_prayer", "holy_fire", "愿明焰垂临此手, 为我焚开前路."),
    ("battle_colloquial", "holy_fire", "把这团火直接推过去, 烧穿前面."),
    ("modern_reference_light", "holy_fire", "来一道像切割炉一样的白热火流, 直直压过去."),
    ("semi_classical_balanced", "wild_fire", "烈焰自前翻起, 先吞那一排敌影."),
    ("semi_classical_literary", "wild_fire", "火浪从身前一掀, 像风里突然立起的赤潮."),
    ("ritual_prayer", "wild_fire", "请使狂焰应我之名, 自前方卷尽来敌."),
    ("battle_colloquial", "wild_fire", "前面那片火给我炸开点, 直接扫过去."),
    ("modern_reference_light", "wild_fire", "给我一阵像喷火器一样的热焰, 朝前面扇过去."),
    ("semi_classical_balanced", "acid_liquid", "酸液出掌, 蚀开前墙."),
    ("semi_classical_literary", "acid_liquid", "那股刺鼻的腐蚀液贴地漫去, 一路把石面咬得发黑."),
    ("ritual_prayer", "acid_liquid", "愿蚀液听我所召, 先替我穿开此壁."),
    ("battle_colloquial", "acid_liquid", "把那团酸的给我泼过去, 先烂掉他的护甲."),
    ("modern_reference_light", "acid_liquid", "来一股像工业强酸一样的液体, 直接冲他身上."),
    ("semi_classical_balanced", "poison_smoke", "毒烟低起, 先迷来敌."),
    ("semi_classical_literary", "poison_smoke", "暗雾在脚前一层层翻开, 像冷夜把人慢慢吞进去."),
    ("ritual_prayer", "poison_smoke", "请使瘴气应声而生, 缠住前方来者."),
    ("battle_colloquial", "poison_smoke", "把那片毒雾给我罩过去, 别让他们看清."),
    ("modern_reference_light", "poison_smoke", "来一团像化学烟一样的毒云, 先糊住前面那几个人."),
    ("semi_classical_balanced", "frost_breath", "寒息出唇, 封其前行."),
    ("semi_classical_literary", "frost_breath", "冷白的霜气自唇边一线压出, 前路还未触及便先结了壳."),
    ("ritual_prayer", "frost_breath", "愿霜息从我口边降下, 先封住此路."),
    ("battle_colloquial", "frost_breath", "这口冷气直接给我压过去, 先冻住他."),
    ("modern_reference_light", "frost_breath", "来一股像液氮泄出来的白冷雾, 从我嘴前冲过去."),
    ("semi_classical_balanced", "ice_shards", "冰棱并起, 直取前敌."),
    ("semi_classical_literary", "ice_shards", "碎亮的寒晶自前上方迸开, 像一群白刃同时翻身向前."),
    ("ritual_prayer", "ice_shards", "请令寒晶应我之声, 穿彼当前身."),
    ("battle_colloquial", "ice_shards", "把那些冰刺给我打出去, 直接钉他."),
    ("modern_reference_light", "ice_shards", "来一排像爆开的玻璃冰片那样的碎锋, 往他脸上掼过去."),
    ("semi_classical_balanced", "stone_spear", "石锋起地, 贯向前身."),
    ("semi_classical_literary", "stone_spear", "脚前的地面忽然鼓起, 像沉骨顶破土层, 直直把石锋送上来."),
    ("ritual_prayer", "stone_spear", "愿地骨听命, 于我足前升起石锋."),
    ("battle_colloquial", "stone_spear", "地上那根石枪给我顶起来, 直接捅过去."),
    ("modern_reference_light", "stone_spear", "来一根像液压桩顶上来的石柱, 从地上狠狠干出去."),
    ("semi_classical_balanced", "iron_sand", "铁砂成潮, 磨穿其甲."),
    ("semi_classical_literary", "iron_sand", "细黑的砂流卷起时像一群小刀, 顺着甲片的缝一路钻进去."),
    ("ritual_prayer", "iron_sand", "请使铁砂循我所指, 缠磨前敌."),
    ("battle_colloquial", "iron_sand", "把那片铁砂给我卷过去, 先磨掉他那层壳."),
    ("modern_reference_light", "iron_sand", "来一团像砂轮碎屑一样的金属砂, 朝他全身刮过去."),
    ("semi_classical_balanced", "lightning_arc", "雷光出掌, 咬住前敌."),
    ("semi_classical_literary", "lightning_arc", "白亮的电芒从掌心一折而起, 像一条暴躁的裂痕忽然追上前人."),
    ("ritual_prayer", "lightning_arc", "愿霹光因我而起, 即刻裁落前敌."),
    ("battle_colloquial", "lightning_arc", "那道电给我连上去, 别让他跑."),
    ("modern_reference_light", "lightning_arc", "来一束像高压电弧那样的白光, 直接劈他."),
    ("semi_classical_balanced", "sticky_tar", "黑沥漫地, 缚其双足."),
    ("semi_classical_literary", "sticky_tar", "那团焦黑的黏流一铺开, 就像夜色先一步爬上了他的脚面."),
    ("ritual_prayer", "sticky_tar", "请使黏黑之沥应我而生, 困其步履."),
    ("battle_colloquial", "sticky_tar", "把那摊黑黏的给我铺到他脚下, 粘死他."),
    ("modern_reference_light", "sticky_tar", "来一层像热沥青一样的东西, 直接封他脚底."),
    ("semi_classical_balanced", "radiant_dust", "辉尘随风起, 亮我前行路."),
    ("semi_classical_literary", "radiant_dust", "细亮的微尘从掌前飘散出去, 像有人把星子轻轻揉进了风里."),
    ("ritual_prayer", "radiant_dust", "愿微光如尘而降, 为我照明此路."),
    ("battle_colloquial", "radiant_dust", "把那些发亮的粉末给我洒出去, 先照清前面."),
    ("modern_reference_light", "radiant_dust", "来一把像反光粉一样的亮尘, 顺着路往前撒开."),
    ("semi_classical_balanced", "lava_pool", "熔流出地, 向前缓压."),
    ("semi_classical_literary", "lava_pool", "脚前翻开的灼液像一朵迟到的火花, 一落地便把整片地面烧得发红."),
    ("ritual_prayer", "lava_pool", "请使熔火应我所唤, 自地而开, 向前而行."),
    ("battle_colloquial", "lava_pool", "前面那滩热的给我涌过去, 烫穿那块地."),
    ("modern_reference_light", "lava_pool", "来一股像炼钢炉倒出来的熔液, 直接往前推."),
    ("semi_classical_balanced", "thorn_vines", "荆棘生地, 缠其周身."),
    ("semi_classical_literary", "thorn_vines", "地里钻出的刺藤一圈圈拧上去, 像在活人的影子外又长了一层骨."),
    ("ritual_prayer", "thorn_vines", "愿刺藤闻我之声, 攀缚前敌."),
    ("battle_colloquial", "thorn_vines", "把那堆藤子给我从地里掀出来, 直接缠住他."),
    ("modern_reference_light", "thorn_vines", "来一片像带刺铁丝一样疯长的藤蔓, 先锁住那个人."),
    ("semi_classical_balanced", "liquid_metal", "银流出掌, 穿隙而过."),
    ("semi_classical_literary", "liquid_metal", "那线明亮的银液细细抽出, 像一条冷光在破绽里无声滑行."),
    ("ritual_prayer", "liquid_metal", "请使液银从我掌前流出, 切开彼身之隙."),
    ("battle_colloquial", "liquid_metal", "把那道银色的液体给我送过去, 钻他露出来的空档."),
    ("modern_reference_light", "liquid_metal", "来一股像水银一样发亮的液态金属, 顺着他躲开的缝穿过去."),
    ("semi_classical_balanced", "ash_cloud", "灰雾回卷, 先蒙追兵."),
    ("semi_classical_literary", "ash_cloud", "温热的灰气从身后翻起, 像熄火后的夜还留着一点喘息."),
    ("ritual_prayer", "ash_cloud", "愿灰霭循我身后而起, 先蔽来敌耳目."),
    ("battle_colloquial", "ash_cloud", "那片灰烟给我兜回来, 先把后面的人盖住."),
    ("modern_reference_light", "ash_cloud", "来一团像工地扬尘一样的热灰, 从后面卷过去."),
    ("semi_classical_balanced", "honey_glue", "稠蜜铺地, 黏住来身."),
    ("semi_classical_literary", "honey_glue", "那股拉丝的金稠液一落下去, 就把地和脚黏成了一回事."),
    ("ritual_prayer", "honey_glue", "请使稠甜之液因我而下, 缚其步履."),
    ("battle_colloquial", "honey_glue", "把那团像蜂蜜一样的给我糊过去, 先黏住他."),
    ("modern_reference_light", "honey_glue", "来一滩像工业胶一样的粘甜液, 直接封他脚下."),
    ("semi_classical_balanced", "glass_rain", "晶锋如雨, 倾落前场."),
    ("semi_classical_literary", "glass_rain", "透明的碎锋从前上方密密坠下, 像一场无声的冷雨忽然有了边."),
    ("ritual_prayer", "glass_rain", "愿清晶应召而裂, 倾作一场锋雨."),
    ("battle_colloquial", "glass_rain", "把那阵玻璃渣一样的给我撒下去, 直接刮他们一脸."),
    ("modern_reference_light", "glass_rain", "来一阵像钢化玻璃炸开的碎片雨, 从上面泼下来."),
    ("semi_classical_balanced", "salt_crystal", "盐霜并起, 封其创口."),
    ("semi_classical_literary", "salt_crystal", "白色的细晶沿着风一层层结上去, 像寒意忽然学会了长出棱角."),
    ("ritual_prayer", "salt_crystal", "请使白盐因我而凝, 覆其身前."),
    ("battle_colloquial", "salt_crystal", "把那层结晶给我压过去, 先把前面封住."),
    ("modern_reference_light", "salt_crystal", "来一片像速冻结霜一样的盐白晶层, 直接扑过去."),
    ("semi_classical_balanced", "paper_flood", "纸页成潮, 压向前阵."),
    ("semi_classical_literary", "paper_flood", "成堆的薄纸一翻出去, 像屋里所有没写完的白页忽然一齐有了重量."),
    ("ritual_prayer", "paper_flood", "愿纸山闻我所唤, 倾落前场."),
    ("battle_colloquial", "paper_flood", "把那堆纸给我全推过去, 先埋了他们."),
    ("modern_reference_heavy", "paper_flood", "来一山像试卷崩下来一样的纸页, 直接往前压."),
    ("semi_classical_balanced", "laser_like_light", "白光成线, 直断前身."),
    ("semi_classical_literary", "laser_like_light", "那道灼白的细光从掌前剖出去, 像空气先被切开, 然后才轮到人影."),
    ("ritual_prayer", "laser_like_light", "请使白灼之光因我而直落, 裁开前敌."),
    ("battle_colloquial", "laser_like_light", "那道白光给我直接扫过去, 别偏."),
    ("modern_reference_heavy", "laser_like_light", "来一束像激光切割一样的灼热线, 直直划过去."),
]

EXTRA_SEED_SPELLS_V2 = [
    ("everyday_clean", "holy_fire", "前面给我放一股白热火, 先把路烧出来."),
    ("everyday_clean", "wild_fire", "把那片乱烧的火往前推, 别让他们靠近."),
    ("everyday_clean", "acid_liquid", "来一滩酸液铺过去, 先把墙面咬开."),
    ("everyday_clean", "poison_smoke", "前面放点毒烟, 先把他们视线糊住."),
    ("everyday_clean", "frost_breath", "来一口冷白的寒气, 先封住那条路."),
    ("everyday_clean", "ice_shards", "在我前面打出一排冰刺, 直接扎过去."),
    ("everyday_clean", "stone_spear", "从地上顶一截石枪出来, 朝前面送过去."),
    ("everyday_clean", "iron_sand", "放一片铁砂出去, 先把那层甲磨掉."),
    ("everyday_clean", "lightning_arc", "给我一道电弧, 直接连到他身上."),
    ("everyday_clean", "sticky_tar", "铺一层黑黏液到他脚下, 别让他抬腿."),
    ("everyday_clean", "radiant_dust", "撒一片会发光的细尘, 把前面照清."),
    ("everyday_clean", "lava_pool", "脚前放一滩灼液, 让它慢慢往前淌."),
    ("everyday_clean", "thorn_vines", "从地里翻出一圈藤刺, 先把他缠住."),
    ("everyday_clean", "liquid_metal", "放一股银色液体过去, 顺着空隙穿."),
    ("everyday_clean", "ash_cloud", "身后卷一片热灰回来, 先盖住追兵."),
    ("everyday_clean", "honey_glue", "来一团稠得像蜂蜜的东西, 先把人黏住."),
    ("everyday_clean", "glass_rain", "从上面落一阵玻璃碎片, 先刮他们一脸."),
    ("everyday_clean", "salt_crystal", "放一层盐白结晶过去, 把前面封住."),
    ("everyday_clean", "paper_flood", "推一堆纸页过去, 先把他们埋进去."),
    ("everyday_clean", "laser_like_light", "给我一束灼白细光, 从中间直接切过去."),
    ("colloquial_with_lift", "holy_fire", "把那团白得发烫的火给我送过去, 先替我把前路掀开."),
    ("colloquial_with_lift", "wild_fire", "那片烈焰别在原地闹, 给我卷到前面人堆里去."),
    ("colloquial_with_lift", "acid_liquid", "把这口酸潮往前一甩, 先替我把那层壳蚀穿."),
    ("colloquial_with_lift", "poison_smoke", "那阵毒雾给我低低压过去, 先乱他们的气息."),
    ("colloquial_with_lift", "frost_breath", "这口寒气压出去, 让前面的路先白上一层."),
    ("colloquial_with_lift", "ice_shards", "把冰棱给我一根根绷出去, 直直钉到前面."),
    ("colloquial_with_lift", "stone_spear", "地底那截石锋给我挑出来, 朝他胸口送过去."),
    ("colloquial_with_lift", "iron_sand", "那片铁砂给我拧起来, 顺着甲缝狠狠干进去."),
    ("colloquial_with_lift", "lightning_arc", "这道电别散, 给我咬住前面那个."),
    ("colloquial_with_lift", "sticky_tar", "把黑沥往他脚下一抹, 让他一动就陷住."),
    ("colloquial_with_lift", "radiant_dust", "那些亮尘给我顺风撒出去, 把前路一点点挑亮."),
    ("colloquial_with_lift", "lava_pool", "把脚前那股熔流推开, 让它贴地往前滚."),
    ("colloquial_with_lift", "thorn_vines", "让那圈荆藤从地里醒过来, 爬上他全身."),
    ("colloquial_with_lift", "liquid_metal", "那缕银流给我抽细点, 顺着他的破绽钻过去."),
    ("colloquial_with_lift", "ash_cloud", "身后那层灰雾给我兜起来, 倒卷到追兵脸上."),
    ("colloquial_with_lift", "honey_glue", "那团黏甜的东西给我拍过去, 先把他粘在地上."),
    ("colloquial_with_lift", "glass_rain", "那片晶锋给我泼下来, 像冷雨一样扫一遍."),
    ("colloquial_with_lift", "salt_crystal", "让盐霜顺着风结过去, 先把前面那块地方钉住."),
    ("colloquial_with_lift", "paper_flood", "把那山纸页给我掀过去, 先压得他们抬不起头."),
    ("colloquial_with_lift", "laser_like_light", "这道白热线给我收紧点, 照着中缝直接划过去."),
    ("detail_literary", "holy_fire", "掌心先亮起一点极白的火核, 随后层层翻开成柔而烫的焰潮, 像清晨的日轮被人捏碎了边缘, 一路淌向前方."),
    ("detail_literary", "wild_fire", "那片烈焰不是一下扑出去, 而是先在身前鼓出一层发红的热浪, 再猛地掀成乱卷的火幕, 把前面的影子一层层吞没."),
    ("detail_literary", "acid_liquid", "绿得发亮的腐蚀液从指间滴成细线, 落地后却立刻摊开, 像一块刚被剖开的果肉冒出刺鼻的气, 沿着墙根慢慢把石皮咬穿."),
    ("detail_literary", "poison_smoke", "毒雾先是薄, 后来才厚, 像一层湿冷的纱从脚边缓缓抬起, 带着发苦的气味贴着人群的胸口和面颊往里钻."),
    ("detail_literary", "frost_breath", "寒气从唇边吐出去时还只是淡白, 到半途却忽然收紧成一道发蓝的冷线, 所过之处连空气都像被谁悄悄擦出了霜."),
    ("detail_literary", "ice_shards", "冰棱不是一根, 而是数枚细长的寒晶在前上方同时亮起, 每一枚边缘都带着薄白的碎光, 甩出去时像一群沉默的短刃."),
    ("detail_literary", "stone_spear", "地面先裂出一条窄黑的缝, 随后石锋从缝里一节节拱起, 带着湿土和碎砂的响声, 像地下有什么沉重的骨头终于顶到了光里."),
    ("detail_literary", "iron_sand", "铁砂被风一卷, 先是暗, 后来才亮, 一粒粒细小的金属光在空中拧成旋, 像有人把无数极薄的刀片磨成了会呼吸的沙."),
    ("detail_literary", "lightning_arc", "电芒从掌心跳出来的瞬间还是细的, 下一刻却沿着半空连成一条发白的裂纹, 像夜色突然被谁用指甲狠狠划了一道口子."),
    ("detail_literary", "sticky_tar", "黑沥落地以后并不急着流, 而是先缓缓摊成一层发亮的暗膜, 厚重得像潮湿的夜被按平在地上, 再一点点爬上脚踝."),
    ("detail_literary", "radiant_dust", "亮尘被扬出去时细得像看不见, 只有在风里转身的一刹那才露出一点点温金的边, 像碎星被揉开后悄悄撒满了路面."),
    ("detail_literary", "lava_pool", "熔流在脚前打开时先是钝重的红, 随后才从里面透出刺眼的白, 一边缓慢翻滚, 一边把地面烫得起了暗亮的壳."),
    ("detail_literary", "thorn_vines", "荆藤从土里钻出来的时候带着很轻的撕裂声, 像一群细黑的指节依次张开, 叶影还没看清, 刺已经先挂住了人的衣角."),
    ("detail_literary", "liquid_metal", "银液抽出时很细, 却一点都不软, 它沿着空隙贴过去的时候像一缕没有温度的光, 安静得几乎听不见, 只有被切开的地方最先发亮."),
    ("detail_literary", "ash_cloud", "热灰从身后卷起来时并不高, 只是一层松散的雾慢慢回收, 颜色像烧尽以后还发烫的纸边, 一扑到人脸上就把呼吸和视线一起抹暗."),
    ("detail_literary", "honey_glue", "那团稠蜜落下去的时候拖着很长的丝, 金得近乎发白, 黏住地面的瞬间又缓慢向四周牵开, 像一层会拉人的网刚刚苏醒."),
    ("detail_literary", "glass_rain", "晶片从前上方落下来时先是无声, 只有掠过光线的时候才一闪, 每一块都薄得像雨, 冷得像刀, 落到人群边上时才忽然显出密."),
    ("detail_literary", "salt_crystal", "白色的细晶沿风推过去, 起初只像薄灰, 越往前却越结越厚, 棱角一层层堆起来, 像寒冷忽然学会了长出自己的甲壳."),
    ("detail_literary", "paper_flood", "纸页冲出去的时候并不散乱, 反而是一层压着一层往前翻, 边角在风里发出干涩的擦声, 像整座屋子的白页忽然都有了重量."),
    ("detail_literary", "laser_like_light", "那束白线最先切开的不是人, 而是空气, 它从掌前笔直推出去的时候细得像一根被拉紧的弦, 边缘却烫得能把影子也烧出焦痕."),
    ("hacky_clever", "holy_fire", "给我一股只烧装备不烧人的火, 先把他那身东西全点了."),
    ("hacky_clever", "wild_fire", "来一片会自己找人钻缝的火, 能进去的地方都给它进去."),
    ("hacky_clever", "acid_liquid", "来点F, 谁挡在前面就先给它咬掉."),
    ("hacky_clever", "poison_smoke", "来一口能摧毁一切事物的气体, 先往前推, 看这个世界到底认不认."),
    ("hacky_clever", "frost_breath", "给我一阵只冻关节不冻武器的冷雾, 先把他腿脚锁死."),
    ("hacky_clever", "ice_shards", "来一排会拐弯找眼缝的冰刺, 让盾牌别装有用."),
    ("hacky_clever", "stone_spear", "地上给我顶一根专门卡碰撞箱的石柱, 让他一步都挪不出去."),
    ("hacky_clever", "iron_sand", "把铁砂做成只磨护甲判定不磨皮肉的那种, 先把数值刮空."),
    ("hacky_clever", "lightning_arc", "来一道会自动续到下一个目标的电, 只要站得近就别想躲."),
    ("hacky_clever", "sticky_tar", "给我一滩只黏脚不黏墙的黑沥, 先把他的位移废掉."),
    ("hacky_clever", "radiant_dust", "撒一层会把潜行判定全点亮的亮尘, 谁藏都给我显出来."),
    ("hacky_clever", "lava_pool", "来一股只烫地形不烫我自己的熔流, 先把前面那片地掀掉."),
    ("hacky_clever", "thorn_vines", "让这堆藤刺优先找关节和武器缝, 哪里好卡就先卡哪里."),
    ("hacky_clever", "liquid_metal", "给我一股会顺着最小缝隙钻进去的银流, 看他还怎么靠判定躲."),
    ("hacky_clever", "ash_cloud", "来一片专门糊视野不糊队友的热灰, 后面那帮人一个也别看清."),
    ("hacky_clever", "honey_glue", "给我一团高得离谱的黏度, 只要沾上就按陷地里算."),
    ("hacky_clever", "glass_rain", "从上面给我落一阵只吃护盾耐久的碎晶雨, 先把那层壳磨没."),
    ("hacky_clever", "salt_crystal", "放一层会沿着潮气自己结壳的盐霜, 哪里湿就先把哪里封死."),
    ("hacky_clever", "paper_flood", "来一山试卷一样的纸, 只要被埋进去就默认出不来."),
    ("hacky_clever", "laser_like_light", "给我一束能把所有东西都切开的线, 先看看程序敢不敢真给我过."),
    ("modern_reference_heavy", "holy_fire", "来一点像U235临界前那样发白发烫的东西, 先往前压看看."),
    ("modern_reference_heavy", "wild_fire", "把这片火做成燃料泄爆那种疯劲, 直接灌穿前面那排."),
    ("modern_reference_heavy", "acid_liquid", "来一股像氢氟酸一样的液体, 先把能咬的全咬了."),
    ("modern_reference_heavy", "poison_smoke", "给我放一股Cl2过去, 先看谁的肺先撑不住."),
    ("modern_reference_heavy", "frost_breath", "来一口像液氦跑出来的冷雾, 先把前面这一条线全冻脆."),
    ("modern_reference_heavy", "ice_shards", "给我一排像碎防爆玻璃一样的冰片, 直接崩到人脸上."),
    ("modern_reference_heavy", "stone_spear", "来根像隧道盾构刀盘一样的石柱, 从地里狠狠干出来."),
    ("modern_reference_heavy", "iron_sand", "把铁砂卷成一片像角磨机火花那样的东西, 贴着他身上磨过去."),
    ("modern_reference_heavy", "lightning_arc", "来一道像变电站短路那样的电弧, 谁在前面谁先吃满."),
    ("modern_reference_heavy", "sticky_tar", "给我一层像机场跑道刚铺好的热沥青, 直接封死他脚底."),
    ("modern_reference_heavy", "radiant_dust", "来一把像镁粉炸亮前那样的细尘, 先把前面全照白."),
    ("modern_reference_heavy", "lava_pool", "给我一股像转炉口翻出来的熔浆, 往前面整片地上灌."),
    ("modern_reference_heavy", "thorn_vines", "让这堆刺藤长得像带倒钩的钢丝网, 先从地里一把翻出来."),
    ("modern_reference_heavy", "liquid_metal", "来一股像汞一样发亮的液态金属, 顺着他让出来的缝狠狠干穿."),
    ("modern_reference_heavy", "ash_cloud", "给我一团像火灾现场回卷的粉热灰, 先把后面那群人呛住."),
    ("modern_reference_heavy", "honey_glue", "来一坨像工业糖浆混强力胶的东西, 拍上去就别想撕开."),
    ("modern_reference_heavy", "glass_rain", "从上头落一阵像碎实验烧杯一样的晶片, 刮过去别留完整面."),
    ("modern_reference_heavy", "salt_crystal", "来一层像冷库里一夜爬满墙的白霜硬壳, 哪儿潮就先封哪儿."),
    ("modern_reference_heavy", "paper_flood", "把那堆比高考卷还离谱的纸页全给我推过去, 看看谁先被埋没."),
    ("modern_reference_heavy", "laser_like_light", "给我一条像工业切割激光那样的白线, 从中间一直剖到头."),
]


def main() -> None:
    recipe_lookup = {item.recipe_id: item for item in STYLE_RECIPES}
    rows = []
    all_seed_spells = SEED_SPELLS_V2 + EXTRA_SEED_SPELLS_V2
    for index, (recipe_id, motif_id, text) in enumerate(all_seed_spells, start=1):
        recipe = recipe_lookup[recipe_id]
        rows.append(
            {
                "id": f"manual_spell_seed_{index:04d}",
                "text": text,
                "meta": {
                    "source": "assistant_manual_seed",
                    "recipe_id": recipe.recipe_id,
                    "recipe_name": recipe.name,
                    "motif_id": motif_id,
                    "politeness_target": recipe.politeness,
                },
            }
        )
    output_path = ROOT / "data" / "source" / "manual_spell_seeds.jsonl"
    write_jsonl(output_path, rows)
    print(f"wrote {len(rows)} seed spells to {output_path}")


if __name__ == "__main__":
    main()
